rt-app: add json bits header file
when we execute 'make' command, we meet error message as follows.

./rt-app/src/rt-app_parse_config.c:773:
undefined reference to `is_error'

Let's append  <json-c/bits.h> header file into rt-app_parse_config.c

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>
[fix minor typo]
[use json-c path instead of json]
Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>